// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_University_Inscription.Data;

namespace Mvc_University_Inscription.Data.Migrations
{
    [DbContext(typeof(MvcUniversityContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId_Course")
                        .HasColumnType("int");

                    b.Property<int>("Studentsid_Student")
                        .HasColumnType("int");

                    b.HasKey("CoursesId_Course", "Studentsid_Student");

                    b.HasIndex("Studentsid_Student");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Admin", b =>
                {
                    b.Property<int>("Id_Admin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Admin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Course", b =>
                {
                    b.Property<int>("Id_Course")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Max_Quota")
                        .HasColumnType("int");

                    b.Property<string>("Name_Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeacherId_Teacher")
                        .HasColumnType("int");

                    b.HasKey("Id_Course");

                    b.HasIndex("TeacherId_Teacher");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Student", b =>
                {
                    b.Property<int>("id_Student")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Student");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Teacher", b =>
                {
                    b.Property<int>("Id_Teacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("First_Name_Teacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name_Teacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Teacher");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("Mvc_University_Inscription.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId_Course")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mvc_University_Inscription.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("Studentsid_Student")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Course", b =>
                {
                    b.HasOne("Mvc_University_Inscription.Models.Teacher", "Teacher")
                        .WithMany("Course")
                        .HasForeignKey("TeacherId_Teacher");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Mvc_University_Inscription.Models.Teacher", b =>
                {
                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
